-- Datos iniciales para desarrollo local.

INSERT INTO AREA (TX_NOMBRE, TX_DESCRIPCION, DN_USUARIO_CREADOR)
VALUES ('COCINA', 'PREPARACION DE ALIMENTOS', 0),
       ('RECEPCION', 'ATENCION A CLIENTES', 0),
       ('MANTENIMIENTO', 'LIMPIEZA E INFRAESTRUCTURA', 0)
ON CONFLICT DO NOTHING;
